### ISSUE TITLE
tornadorpc package in pip server doesn't have README.md file

### ISSUE THREAD

**Issue by scottbelden** [joshmarshall/tornadorpc#7]
It appears that the package uploaded to the pip server doesn't have "README.md" but instead just has "README". Therefore, the setup fails on line 5 when it can't open README.md. Below is the output I get:

```
$ pip install tornadorpc
Downloading/unpacking tornadorpc
  Downloading tornadorpc-0.1.1.tar.gz
  Running setup.py egg_info for package tornadorpc
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/vagrant/build/tornadorpc/setup.py", line 5, in <module>
        with open("README.md") as readme:
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/vagrant/build/tornadorpc/setup.py", line 5, in <module>

    with open("README.md") as readme:

IOError: [Errno 2] No such file or directory: 'README.md'

----------------------------------------
Command python setup.py egg_info failed with error code 1
```

**Comment by marcel-becker** [comment]
Same problem here.

**Comment by joshmarshall** [comment]
Woops! Tried to consolidate documentation.

Just pushed a fixed to PyPI. Let me know if you have any other issues!

**Comment by scottbelden** [comment]
Thanks for the fix!
